# Generated by Django 4.1.3 on 2022-11-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                default="Cliente", max_length=45, verbose_name="Cargo"
            ),
        ),
    ]
